language: python
python:
  #- "2.7" should work without orjson
  #- "3.4" should work without orjson
  #- "3.5" should work without orjson
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch

# command to install dependencies
install:
  #- pip install -r requirements.txt
  - pip install orjson
  - pip install dictdiffer
  - pip install coverage
  - pip install coveralls || true
# command to run tests
script:
  - coverage run --source=./IIIFpres/ --omit=./IIIFpres/MediaTypes.py -m unittest discover -s tests/

  after_success:
  coveralls || true